#!/usr/bin/python3

import os
import stat
import sys
import time
from ctypes import *
import socket
import threading

def receive_data(sock):
    global remote_addr
    while True:
        try:
            data, remote_addr = sock.recvfrom(1024)  # Buffer size is 1024 bytes
            print(f"Received {len(data)} bytes from {remote_addr}")
            betaflight.slpi_link_send(data, c_ulong(len(data)))
        except Exception as e:
            print(f"Error receiving data: {e}")
            break


def py_cb_func(data, len):
    global remote_addr
    global pipe
    global pipe_open

    # print('Got data callback')

    data_array = cast(data, POINTER(c_ubyte))
    if data_array[0] == 0x5A:
        print("Got MSP data for configurator: " + str(len) + " bytes")
        binary_data = bytearray(len-1)
        for i in range(1,len):
            binary_data[i-1] = data_array[i]

        # print(f"Sending {len - 1} bytes to {remote_addr}")
        # print(binary_data)

        sock.sendto(binary_data, remote_addr)
    elif data_array[0] == 0xA5:
        # print("Got OSD data packet: " + str(len) + " bytes")
        if pipe_open:
            binary_data = bytearray(len-1)
            for i in range(1,len):
                binary_data[i-1] = data_array[i]
            pipe.write(binary_data)
            pipe.flush() # Ensure data is sent immediately
    else:
        print("Got unknown data packet" + str(data_array[0]))

def check_named_pipe_existence(pipe_path):
    """
    Checks if a named pipe exists at the given path.

    Args:
        pipe_path: The path to the named pipe.

    Returns:
        True if the named pipe exists, False otherwise.
    """
    try:
        mode = os.stat(pipe_path).st_mode
        return stat.S_ISFIFO(mode)
    except FileNotFoundError:
        return False

#### MAIN ####

remote_addr = ''

pipe_path = "/tmp/osd_pipe"
pipe_open = False
if check_named_pipe_existence(pipe_path):
    try:
        pipe = open(pipe_path, 'wb')
        pipe_open = True
    except:
        pass

betaflight = CDLL('libslpi_link.so.1')

# typedef void (*slpi_link_cb)(const uint8_t *data, uint32_t length_in_bytes);
CBFUNC = CFUNCTYPE(None, POINTER(c_ubyte), c_ulong)
cb_func = CBFUNC(py_cb_func)

print('Calling slpi_link_init')

# int slpi_link_init(bool enable_debug_messages, slpi_link_cb callback, const char *library_name);
result = betaflight.slpi_link_init(False, cb_func, b'betaflight.so')

print('slpi_link_init returned: ' + str(result))

# Create a UDP socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

# Bind the socket to the address and port
server_address = ('', 8765) # '' means any available interface
sock.bind(server_address)

receive_thread = threading.Thread(target=receive_data, args=(sock,), daemon=True)
receive_thread.start()

while True:
    try:
        time.sleep(0.2)
    except:
        print('Got unknown exception')
        break

sock.close()

# void slpi_link_reset(void);
betaflight.slpi_link_reset(None)

